### ISSUE TITLE
Compact Machines Chamber no longer crafts walls, etc

### ISSUE THREAD

**Issue by MechOrigin** [userTravis/Chambers#10]
* Chambers Mod version: 1.4.5
* Mod Version of the Mod the Chamber you are having issues with is designed to work with: compactmachines3-1.12.2-3.0.18-b278
* Minecraft Forge version: 1.12.2
* Mod Pack: (if applicable): 

## Steps to reproduce
1. Put Iron Block and Redstone dust in chamber and it does nothing.
2. Etc...

**Comment by userTravis** [comment]
Works fine for me, are you sure you're using the "Field Projector Chamber" and not the "Large Field Projector Chamber." Also just out of curiosity have you tried breaking and replacing the Chamber block?(this should not be needed but would be good to rule it out)
EDIT: remember the wall recipe calls for 2 redstone dust

**Comment by userTravis** [comment]
Closing this as I have not heard back(My test environment does not exhibit the issue described, will reopen if more info is provided)
