### ISSUE TITLE
Crash on startup with the recent update

### ISSUE THREAD

**Issue by TheComputerizer** [userTravis/Chambers#11]
I just updated to the newest version of chambers that adds support for embers and got a crash when loading up my modpack. Here is the [crash report](https://pastebin.com/qGFNXSNP). It is probably worth noting that my pack does not have embers installed.

**Comment by userTravis** [comment]
For some reason it does not crash in my test environment, but this should work. Please confirm before I push it to curse.
-Link Removed-
EDIT: file is released on curse now so I'm closing this.

**Comment by TheComputerizer** [comment]
Yeah that seems to have fixed the issue. Thanks for the quick response
