### ISSUE TITLE
Add a slot in the atomic reconstructor chamber for lenses

### ISSUE THREAD

**Issue by winterSteve25** [userTravis/Chambers#4]
As I know you currently can not do lens craftings with the atomic reconstructor, it would be great if that is a feature. Ignore me if it is already a thing :)

**Comment by userTravis** [comment]
Which lenses would you like to see added? According to the [wiki](https://ftb.gamepedia.com/Atomic_Reconstructor) most lenses perform in-world actions which would not work in a GUI such as damaging a mob or creating an explosion.

**Comment by winterSteve25** [comment]
Maybe like the colored one and the disenchanting one?

**Comment by userTravis** [comment]
Just got internet service turned on at my new place, still got a lot to unpack, please be patient it may be some time before this gets worked on.

**Comment by winterSteve25** [comment]
Ok not a big issue anyways, but I did submit another major bug, maybe you could take a look at that first :) thanks

**Comment by userTravis** [comment]
Request approved: support for lenses has been added to Chambers in version 1.4.4*
*Lens of the Miner/Lens of Color/Lens of Disenchanting

Thank you for being patient, please let me know if you find any bugs.
