### ISSUE TITLE
[Empower Chamber] Delete output item when there is already something in the output slot

### ISSUE THREAD

**Issue by winterSteve25** [userTravis/Chambers#5]
## Basic information
* Chambers Mod version: 1.4.1
* Minecraft Forge version: 2854
* Mod Pack: (if applicable): FictionCraft: Atomic Space

## Crash report
No crash report

Screenshots are VERY helpful in explaining an issue.
## Steps to reproduce
1. Put item inputs in the input slots
2. Accelerate block tick speed (time in a bottle / imaginary time block / astral ritual)
3. The output amount is 8 but when accelerating the output becomes 1 ( I think it only happens when there is something in the output slot already, not sure)

Also a quick suggestion, maybe optimize the CapabilityItemHandler so the input slot wont be extracted when using a pipe to extract item from the chambers

**Comment by winterSteve25** [comment]
Actually just tested again, acceleration doesn't matter, it just deletes output when there is something in the output slot already

**Comment by userTravis** [comment]
Which recipe(s) does this occur on? All ActuallyAdditions default recipes appear to function fine for me.

**Comment by userTravis** [comment]
Looking in that ModPacks CraftTweaker scripts I see it has output itemstack quantities greater then 1, I did not know this was possible for Empowerer recipes. I should be able to fix this tomorrow.

**Comment by winterSteve25** [comment]
Thanks!

**Comment by userTravis** [comment]
Does this fix work? I patched the Empowerer/Reconstruction/Compost Chambers as they all appear to be effected by this bug.
[Chambers-1.4.2.zip](https://github.com/userTravis/Chambers/files/5953599/Chambers-1.4.2.zip) (Jar in Zip because GitHub does not support Jar file uploads)

**Comment by winterSteve25** [comment]
Yep it is fixed now

**Comment by winterSteve25** [comment]
When should I expect the next update to come on curseforge?

**Comment by userTravis** [comment]
New update 1.4.2 fixes this and is released on Curse(curse sometimes takes a few minutes to approve the file)
