### ISSUE TITLE
Empowerer Chamber does not work when the power usage for the recipe is over 320000

### ISSUE THREAD

**Issue by TheComputerizer** [userTravis/Chambers#6]
## Basic information
* Chambers Version: 1.4.2
* Actually Additions Version: 1.12.2-r152
* Minecraft Forge Version: 14.23.5.2854
* Modpack: DimensionHopper

## Description of the Issue
When a custom recipe for the empowerer is added via Crafttweaker and the total power usage is set above 320000 RF, the empowerer chamber will not even start the recipe.

Here is a [video]( https://streamable.com/8hzxrk) showcasing the issue. The first recipe requires under 320000 RF and works. The second recipe requires over 320000 RF and does not work in the empowerer chamber, but it starts just fine when using a normal empowerer

## Steps to reproduce
1. Create custom recipe for the empowerer via Crafttweaker and set the power usage over 320000
2. Empowerer chamber does not start the recipe

**Comment by userTravis** [comment]
The buffer size I originally selected for these Chambers is related to the buffer size of the actual Empowerer/Display Stands in world setup. Is this custom recipe even possible to craft using only the Actually Additions Mod without Chambers? Because I believe each of the four display stand naturally only holds 80k energy maximum, thus I have the Chamber hold 4*80=320k.

**Comment by userTravis** [comment]
Hmm, this may require an overhaul of the way Chambers uses energy, I presume fixing this will take some time.

Currently Chambers are programmed to wait to begin crafting until there is enough energy available to perform the given recipe. It seems custom recipes are allowed to use an amount of energy greater then the internal buffers of the Display Stands, this is fixable, but it will not be fixed overnight.

**Comment by TheComputerizer** [comment]
Yeah no problem, just wanted to let you know

**Comment by userTravis** [comment]
Does this work?
[Chambers-1.4.3.zip](https://github.com/userTravis/Chambers/files/5975809/Chambers-1.4.3.zip)(jar in zip because GitHub does not allow jar files)

**Comment by TheComputerizer** [comment]
I tested it with various recipes above 320000 RF all the way up to 7680000 and it seemed to work fine. Thanks for the quick fix!

**Comment by userTravis** [comment]
Glad to hear it, it ended up being a bit simpler then I first thought and it's out on curse now so I'm closing this.
