### ISSUE TITLE
[Suggestion] Adding a Embers Exchanging table chamber

### ISSUE THREAD

**Issue by winterSteve25** [userTravis/Chambers#9]
This could be useful, can try doing something like the de infusion chamber :)

**Comment by userTravis** [comment]
Glancing at the code shows me it should be possible. Tutorials(in English) are very few for Embers however, allow me some time to familiarize myself with the mod as to see what kind of Chambers implementation would be the best approach.

**Comment by winterSteve25** [comment]
I think Mischief of Mice has some nice tutorials

**Comment by userTravis** [comment]
How should Ember be used with the recipe? The Exchange Tablet not only uses items in its recipe but also Ember. Ember is not able to be transmitted with wires like RF. If I make the Chamber require Ember, it would make the Chamber not as easily fit into tight spaces, or I could make the Chamber have a "built-in" Activator/Pressure Refinery to allow for all the energy it needs to be generated locally within the Chamber?

Now I am wondering if I should also try to make a Chamber that functions as a complete Activator/Pressure Refinery setup in a single block. I suppose this is a caveat of not having played with the mod, as I do not know how it would be used in-game hah.

**Comment by winterSteve25** [comment]
Haha, my idea was you can use a receiver on the chamber like the modular diversity ember hatches, but you can make it that there is a built-in ember receiver (if that's possible)

**Comment by userTravis** [comment]
Are there other ways to generate Ember other then the Ember Activator/Pressure Refinery?

**Comment by winterSteve25** [comment]
Don't think so, I might be wrong though

**Comment by userTravis** [comment]
Request approved: support for Embers Alchemy(Exchanging Table/Pedestals) has been added to Chambers in version 1.5.0
Tested it the best I could, but please let me know if you find any bugs(or have other feature requests).
